version: '3.8'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"


  gate-simulator:
    build:
      context: ./gate-simulator
    container_name: gate_simulator
    command: npm start
    ports:
      - "9999:9999"
    volumes:
      - ./gate-simulator:/app
    working_dir: /app

