version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  postgres:
#    image: postgres:latest
#    container_name: postgres_container
#    environment:
#      POSTGRES_DB: my_database
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: user_password
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  gate-simulator:
    build:
      context: ./gate-simulator
    container_name: gate_simulator
    command: npm start
    ports:
      - "9999:9999"
    volumes:
      - ./gate-simulator:/app
    working_dir: /app

volumes:
  mysql_data:
  postgres_data:
